version: '3'
services:
  php:
    build: ./php
    volumes:
      - ./data/html:/usr/share/nginx/html
  nginx:
    environment:
      TZ: Asia/Tokyo  
    build: ./nginx
    hostname: nginx01
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    links:
      - tomcat01
  tomcat01:
    build: ./tomcat
    hostname: tomcat01
    ports:
      - "8080:8080"
      - "8443:8443"
    links:
      - redis
      - postgres
  data:
    build: ./data
    volumes:
      - ./data/workspace:/workspace
  cloud9:
    build: ./cloud9
    volumes:
      - ./data/workspace:/workspace
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "18080:80"
      - "15454:15454"
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
  redis:
    build: ./redis
    ports:
      - "6379:6379"
  hrmsDB:
    image: mysql:5.7
    volumes:
      - ./data/hrms_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hrms
      MYSQL_DATABASE: hrms
      MYSQL_USER: hrms
      MYSQL_PASSWORD: hrms
  wordpressDB:
    image: mysql:5.7
    volumes:
      - ./data/wordpress_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    links:
      - wordpressDB
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpressDB01:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
