version: '3'
services:
  php:
    build: ./php
    volumes:
      - ./data/html:/usr/share/nginx/html
  nginx:
    environment:
      TZ: Asia/Tokyo  
    build: ./nginx
    hostname: nginx01
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    links:
      - tomcat01
  tomcat01:
    build: ./tomcat
    hostname: tomcat01
    ports:
      - "8080:8080"
      - "8443:8443"
    links:
      - redis
      - postgres
  data:
    build: ./data
    volumes:
      - ./data/workspace:/workspace
  cloud9:
    build: ./cloud9
    volumes:
      - ./data/workspace:/workspace
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "18080:80"
      - "15454:15454"
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
  redis:
    build: ./redis
    ports:
      - "6379:6379"
