version: '3.4'
services:
  redis:
    build: ./redis
    ports:
      - "6379:6379"
  hrmsdb:
    build: ./hrms
    container_name: hrmsdb
    privileged: true
    volumes:
      - ./data/hrms_data:/var/lib/mysql:delegated
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hrms
      MYSQL_DATABASE: hrms
      MYSQL_USER: hrms
      MYSQL_PASSWORD: hrms
  php:
    image: php:fpm
    privileged: true
    volumes:
      - ./data/html:/usr/share/nginx/html:delegated
    links:
      - hrmsdb
  tomcat:
    image: tomcat:8
    container_name: tomcat
    privileged: true
    volumes:
      - ./data/webapps:/usr/local/tomcat/webapps:delegated
    ports:
      - "8080:8080"
      - "8443:8443"
    links:
      - hrmsdb
  nginx:
    environment:
      TZ: Asia/Tokyo
    build: ./nginx
    container_name: nginx
    privileged: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/html:/usr/share/nginx/html:delegated
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
      - tomcat
      - hrmsdb
#  data:
#    build: ./data
#    volumes:
#      - ./data
#  cloud9:
#    build: ./cloud9
#    volumes:
#      - ./data/workspace:/workspace
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - "18080:80"
#      - "15454:15454"
#  postgres:
#    build: ./postgres
#    ports:
#      - "5432:5432"
#  wordpressDB:
#    image: mysql:5.7
#    volumes:
#      - ./data/wordpress_data:/var/lib/mysql
#    restart: always
#    ports:
#      - "13307:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: somewordpress
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress
#  wordpress:
#    links:
#      - wordpressDB
#    image: wordpress:latest
#    ports:
#      - "8000:80"
#    restart: always
#    environment:
#      WORDPRESS_DB_HOST: wordpressDB:3306
#      WORDPRESS_DB_USER: wordpress
#      WORDPRESS_DB_PASSWORD: wordpress
